import {Arr} from '@ephox/katamari';

import Editor from 'tinymce/core/api/Editor';
import Tools from 'tinymce/core/api/util/Tools';

import * as Options from '../api/Options';

const isArray = Tools.isArray;

export const UserDefined = 'User Defined';

export type Char = [number, string];

export interface CharMap {
  readonly name: string;
  characters: Char[];
}

const getDefaultCharMap = (): CharMap[] => {
  return [
    {
      name: 'Currency',
      characters: [
        [36, 'dollar sign'],
        [162, 'cent sign'],
        [8364, 'euro sign'],
        [163, 'pound sign'],
        [165, 'yen sign'],
        [164, 'currency sign'],
        [8352, 'euro-currency sign'],
        [8353, 'colon sign'],
        [8354, 'cruzeiro sign'],
        [8355, 'french franc sign'],
        [8356, 'lira sign'],
        [8357, 'mill sign'],
        [8358, 'naira sign'],
        [8359, 'peseta sign'],
        [8360, 'rupee sign'],
        [8361, 'won sign'],
        [8362, 'new sheqel sign'],
        [8363, 'dong sign'],
        [8365, 'kip sign'],
        [8366, 'tugrik sign'],
        [8367, 'drachma sign'],
        [8368, 'german penny symbol'],
        [8369, 'peso sign'],
        [8370, 'guarani sign'],
        [8371, 'austral sign'],
        [8372, 'hryvnia sign'],
        [8373, 'cedi sign'],
        [8374, 'livre tournois sign'],
        [8375, 'spesmilo sign'],
        [8376, 'tenge sign'],
        [8377, 'indian rupee sign'],
        [8378, 'turkish lira sign'],
        [8379, 'nordic mark sign'],
        [8380, 'manat sign'],
        [8381, 'ruble sign'],
        [20870, 'yen character'],
        [20803, 'yuan character'],
        [22291, 'yuan character, in hong kong and taiwan'],
        [22278, 'yen/yuan character variant one']
      ]
    },
    {
      name: 'Text',
      characters: [
        [169, 'copyright sign'],
        [174, 'registered sign'],
        [8482, 'trade mark sign'],
        [8240, 'per mille sign'],
        [181, 'micro sign'],
        [183, 'middle dot'],
        [8226, 'bullet'],
        [8230, 'three dot leader'],
        [8242, 'minutes / feet'],
        [8243, 'seconds / inches'],
        [167, 'section sign'],
        [182, 'paragraph sign'],
        [223, 'sharp s / ess-zed']
      ]
    },
    {
      name: 'Quotations',
      characters: [
        [8249, 'single left-pointing angle quotation mark'],
        [8250, 'single right-pointing angle quotation mark'],
        [171, 'left pointing guillemet'],
        [187, 'right pointing guillemet'],
        [8216, 'left single quotation mark'],
        [8217, 'right single quotation mark'],
        [8220, 'left double quotation mark'],
        [8221, 'right double quotation mark'],
        [8218, 'single low-9 quotation mark'],
        [8222, 'double low-9 quotation mark'],
        [60, 'less-than sign'],
        [62, 'greater-than sign'],
        [8804, 'less-than or equal to'],
        [8805, 'greater-than or equal to'],
        [8211, 'en dash'],
        [8212, 'em dash'],
        [175, 'macron'],
        [8254, 'overline'],
        [164, 'currency sign'],
        [166, 'broken bar'],
        [168, 'diaeresis'],
        [161, 'inverted exclamation mark'],
        [191, 'turned question mark'],
        [710, 'circumflex accent'],
        [732, 'small tilde'],
        [176, 'degree sign'],
        [8722, 'minus sign'],
        [177, 'plus-minus sign'],
        [247, 'division sign'],
        [8260, 'fraction slash'],
        [215, 'multiplication sign'],
        [185, 'superscript one'],
        [178, 'superscript two'],
        [179, 'superscript three'],
        [188, 'fraction one quarter'],
        [189, 'fraction one half'],
        [190, 'fraction three quarters']
      ]
    },
    {
      name: 'Mathematical',
      characters: [
        [8704, 'for all'],
        [8705, 'complement'],
        [8706, 'partial differential'],
        [8707, 'there exist'],
        [8708, 'there does not exist'],
        [8709, 'empty set'],
        [8710, 'increment'],
        [8711, 'nabla'],
        [8712, 'element of'],
        [8713, 'not an element of'],
        [8714, 'small element of'],
        [8715, 'contains as member'],
        [8716, 'does not contain as member'],
        [8717, 'small contains as member'],
        [8718, 'end of proof'],
        [8719, 'n-ary product'],
        [8720, 'n-ary coproduct'],
        [8721, 'n-ary summation'],
        [8722, 'minus sign'],
        [8723, 'minus-or-plus sign'],
        [8724, 'dot plus'],
        [8725, 'division slash'],
        [8726, 'set minus'],
        [8727, 'asterisk operator'],
        [8728, 'ring operator'],
        [8729, 'bullet operator'],
        [8730, 'square root'],
        [8731, 'cube root'],
        [8732, 'fourth root'],
        [8733, 'proportional to'],
        [8734, 'infinity'],
        [8735, 'right angle'],
        [8736, 'angle'],
        [8737, 'measured angle'],
        [8738, 'spherical angle'],
        [8739, 'divides'],
        [8740, 'does not divide'],
        [8741, 'parallel to'],
        [8742, 'not parallel to'],
        [8743, 'logical and'],
        [8744, 'logical or'],
        [8745, 'intersection'],
        [8746, 'union'],
        [8747, 'integral'],
        [8748, 'double integral'],
        [8749, 'triple integral'],
        [8750, 'contour integral'],
        [8751, 'surface integral'],
        [8752, 'volume integral'],
        [8753, 'clockwise integral'],
        [8754, 'clockwise contour integral'],
        [8755, 'anticlockwise contour integral'],
        [8756, 'therefore'],
        [8757, 'because'],
        [8758, 'ratio'],
        [8759, 'proportion'],
        [8760, 'dot minus'],
        [8761, 'excess'],
        [8762, 'geometric proportion'],
        [8763, 'homothetic'],
        [8764, 'tilde operator'],
        [8765, 'reversed tilde'],
        [8766, 'inverted lazy s'],
        [8767, 'sine wave'],
        [8768, 'wreath product'],
        [8769, 'not tilde'],
        [8770, 'minus tilde'],
        [8771, 'asymptotically equal to'],
        [8772, 'not asymptotically equal to'],
        [8773, 'approximately equal to'],
        [8774, 'approximately but not actually equal to'],
        [8775, 'neither approximately nor actually equal to'],
        [8776, 'almost equal to'],
        [8777, 'not almost equal to'],
        [8778, 'almost equal or equal to'],
        [8779, 'triple tilde'],
        [8780, 'all equal to'],
        [8781, 'equivalent to'],
        [8782, 'geometrically equivalent to'],
        [8783, 'difference between'],
        [8784, 'approaches the limit'],
        [8785, 'geometrically equal to'],
        [8786, 'approximately equal to or the image of'],
        [8787, 'image of or aproximately equal to'],
        [8788, 'colon equals'],
        [8789, 'equals colon'],
        [8790, 'ring in equal to'],
        [8791, 'ring equal to'],
        [8792, 'corresponds to'],
        [8793, 'estimates'],
        [8794, 'equiangular to'],
        [8795, 'star equals'],
        [8796, 'delta equal to'],
        [8797, 'equal to by definition'],
        [8798, 'measured by'],
        [8799, 'questioned equal to'],
        [8800, 'not equal to'],
        [8801, 'identical to'],
        [8802, 'not identical to'],
        [8803, 'strictly equivalent to'],
        [8804, 'less-than or equal to'],
        [8805, 'greater-than or equal to'],
        [8806, 'less-than over equal to'],
        [8807, 'greater-than over equal to'],
        [8808, 'less-than but not equal to'],
        [8809, 'greater-than but not equal to'],
        [8810, 'much less-than'],
        [8811, 'much greater-than'],
        [8812, 'between'],
        [8813, 'not equivalent to'],
        [8814, 'not less-than'],
        [8815, 'not greater-than'],
        [8816, 'neither less-than nor equal to'],
        [8817, 'neither greater-than nor equal to'],
        [8818, 'less-than or equivalent to'],
        [8819, 'greater-than or equivalent to'],
        [8820, 'neither less-than nor equivalent to'],
        [8821, 'neither greater-than nor equivalent to'],
        [8822, 'less-than or greater-than'],
        [8823, 'greater-than or less-than'],
        [8824, 'neither less-than nor greater-than'],
        [8825, 'neither greater-than nor less-than'],
        [8826, 'precedes'],
        [8827, 'succeeds'],
        [8828, 'precedes or equal to'],
        [8829, 'succeeds or equal to'],
        [8830, 'precedes or equivalent to'],
        [8831, 'succeeds or equivalent to'],
        [8832, 'does not precede'],
        [8833, 'does not succeed'],
        [8834, 'subset of'],
        [8835, 'superset of'],
        [8836, 'not a subset of'],
        [8837, 'not a superset of'],
        [8838, 'subset of or equal to'],
        [8839, 'superset of or equal to'],
        [8840, 'neither a subset of nor equal to'],
        [8841, 'neither a superset of nor equal to'],
        [8842, 'subset of with not equal to'],
        [8843, 'superset of with not equal to'],
        [8844, 'multiset'],
        [8845, 'multiset multiplication'],
        [8846, 'multiset union'],
        [8847, 'square image of'],
        [8848, 'square original of'],
        [8849, 'square image of or equal to'],
        [8850, 'square original of or equal to'],
        [8851, 'square cap'],
        [8852, 'square cup'],
        [8853, 'circled plus'],
        [8854, 'circled minus'],
        [8855, 'circled times'],
        [8856, 'circled division slash'],
        [8857, 'circled dot operator'],
        [8858, 'circled ring operator'],
        [8859, 'circled asterisk operator'],
        [8860, 'circled equals'],
        [8861, 'circled dash'],
        [8862, 'squared plus'],
        [8863, 'squared minus'],
        [8864, 'squared times'],
        [8865, 'squared dot operator'],
        [8866, 'right tack'],
        [8867, 'left tack'],
        [8868, 'down tack'],
        [8869, 'up tack'],
        [8870, 'assertion'],
        [8871, 'models'],
        [8872, 'true'],
        [8873, 'forces'],
        [8874, 'triple vertical bar right turnstile'],
        [8875, 'double vertical bar double right turnstile'],
        [8876, 'does not prove'],
        [8877, 'not true'],
        [8878, 'does not force'],
        [8879, 'negated double vertical bar double right turnstile'],
        [8880, 'precedes under relation'],
        [8881, 'succeeds under relation'],
        [8882, 'normal subgroup of'],
        [8883, 'contains as normal subgroup'],
        [8884, 'normal subgroup of or equal to'],
        [8885, 'contains as normal subgroup or equal to'],
        [8886, 'original of'],
        [8887, 'image of'],
        [8888, 'multimap'],
        [8889, 'hermittan conjugate matrix'],
        [8890, 'intercalate'],
        [8891, 'xor'],
        [8892, 'nand'],
        [8893, 'nor'],
        [8894, 'right angle with arc'],
        [8895, 'right triangle'],
        [8896, 'n-ary logical and'],
        [8897, 'n-ary logical or'],
        [8898, 'n-ary intersection'],
        [8899, 'n-ary union'],
        [8900, 'diamond operator'],
        [8901, 'dot operator'],
        [8902, 'star operator'],
        [8903, 'division times'],
        [8904, 'bowtie'],
        [8905, 'left normal factor semidirect product'],
        [8906, 'right normal factor semidirect product'],
        [8907, 'left semidirect product'],
        [8908, 'right semidirect product'],
        [8909, 'reversed tilde equals'],
        [8910, 'curly logical or'],
        [8911, 'curly logical and'],
        [8912, 'double subset'],
        [8913, 'double superset'],
        [8914, 'double intersection'],
        [8915, 'double union'],
        [8916, 'pitchfork'],
        [8917, 'equal and parallel to'],
        [8918, 'less-than with dot'],
        [8919, 'greater-than with dot'],
        [8920, 'very much less-than'],
        [8921, 'very much greater-than'],
        [8922, 'less-than equal to or greater-than'],
        [8923, 'greater-than equal to or less-than'],
        [8924, 'equal to or less-than'],
        [8925, 'equal to or greater-than'],
        [8926, 'equal to or precedes'],
        [8927, 'equal to or succeeds'],
        [8928, 'does not precede or equal'],
        [8929, 'does not succeed or equal'],
        [8930, 'not square image of or equal to'],
        [8931, 'not square original of or equal to'],
        [8932, 'square image of or not equal to'],
        [8933, 'square original of or not equal to'],
        [8934, 'less-than but not equivalent to'],
        [8935, 'greater-than but not equivalent to'],
        [8936, 'precedes but not equivalent to'],
        [8937, 'succeeds but not equivalent to'],
        [8938, 'not normal subgroup of'],
        [8939, 'does not contain as normal subgroup'],
        [8940, 'not normal subgroup of or equal to'],
        [8941, 'does not contain as normal subgroup or equal'],
        [8942, 'vertival ellipsis'],
        [8943, 'midline horizontal ellipsis'],
        [8944, 'up right diagonal ellipsis'],
        [8945, 'down right diagonal ellipsis'],
        [8946, 'element of with long horizontal stroke'],
        [8947, 'element of with vertical bar at end of horizontal stroke'],
        [8948, 'small element of with vertical bar at end of horizontal stroke'],
        [8949, 'element of with dot above'],
        [8950, 'element of with overbar'],
        [8951, 'small element of with overbar'],
        [8952, 'element of with underbar'],
        [8953, 'element of with two horizontal strokes'],
        [8954, 'contains with long horizontal stroke'],
        [8955, 'contains with vertical bar at end of horizontal stroke'],
        [8956, 'small contains with vertical bar at end of horizontal stroke'],
        [8957, 'contains with overbar'],
        [8958, 'small contains with overbar'],
        [8959, 'z notation bag membership']
      ]
    },
    {
      name: 'Extended Latin',
      characters: [
        [192, 'A - grave'],
        [193, 'A - acute'],
        [194, 'A - circumflex'],
        [195, 'A - tilde'],
        [196, 'A - diaeresis'],
        [197, 'A - ring above'],
        [256, 'A - macron'],
        [198, 'ligature AE'],
        [199, 'C - cedilla'],
        [200, 'E - grave'],
        [201, 'E - acute'],
        [202, 'E - circumflex'],
        [203, 'E - diaeresis'],
        [274, 'E - macron'],
        [204, 'I - grave'],
        [205, 'I - acute'],
        [206, 'I - circumflex'],
        [207, 'I - diaeresis'],
        [298, 'I - macron'],
        [208, 'ETH'],
        [209, 'N - tilde'],
        [210, 'O - grave'],
        [211, 'O - acute'],
        [212, 'O - circumflex'],
        [213, 'O - tilde'],
        [214, 'O - diaeresis'],
        [216, 'O - slash'],
        [332, 'O - macron'],
        [338, 'ligature OE'],
        [352, 'S - caron'],
        [217, 'U - grave'],
        [218, 'U - acute'],
        [219, 'U - circumflex'],
        [220, 'U - diaeresis'],
        [362, 'U - macron'],
        [221, 'Y - acute'],
        [376, 'Y - diaeresis'],
        [562, 'Y - macron'],
        [222, 'THORN'],
        [224, 'a - grave'],
        [225, 'a - acute'],
        [226, 'a - circumflex'],
        [227, 'a - tilde'],
        [228, 'a - diaeresis'],
        [229, 'a - ring above'],
        [257, 'a - macron'],
        [230, 'ligature ae'],
        [231, 'c - cedilla'],
        [232, 'e - grave'],
        [233, 'e - acute'],
        [234, 'e - circumflex'],
        [235, 'e - diaeresis'],
        [275, 'e - macron'],
        [236, 'i - grave'],
        [237, 'i - acute'],
        [238, 'i - circumflex'],
        [239, 'i - diaeresis'],
        [299, 'i - macron'],
        [240, 'eth'],
        [241, 'n - tilde'],
        [242, 'o - grave'],
        [243, 'o - acute'],
        [244, 'o - circumflex'],
        [245, 'o - tilde'],
        [246, 'o - diaeresis'],
        [248, 'o slash'],
        [333, 'o macron'],
        [339, 'ligature oe'],
        [353, 's - caron'],
        [249, 'u - grave'],
        [250, 'u - acute'],
        [251, 'u - circumflex'],
        [252, 'u - diaeresis'],
        [363, 'u - macron'],
        [253, 'y - acute'],
        [254, 'thorn'],
        [255, 'y - diaeresis'],
        [563, 'y - macron'],
        [913, 'Alpha'],
        [914, 'Beta'],
        [915, 'Gamma'],
        [916, 'Delta'],
        [917, 'Epsilon'],
        [918, 'Zeta'],
        [919, 'Eta'],
        [920, 'Theta'],
        [921, 'Iota'],
        [922, 'Kappa'],
        [923, 'Lambda'],
        [924, 'Mu'],
        [925, 'Nu'],
        [926, 'Xi'],
        [927, 'Omicron'],
        [928, 'Pi'],
        [929, 'Rho'],
        [931, 'Sigma'],
        [932, 'Tau'],
        [933, 'Upsilon'],
        [934, 'Phi'],
        [935, 'Chi'],
        [936, 'Psi'],
        [937, 'Omega'],
        [945, 'alpha'],
        [946, 'beta'],
        [947, 'gamma'],
        [948, 'delta'],
        [949, 'epsilon'],
        [950, 'zeta'],
        [951, 'eta'],
        [952, 'theta'],
        [953, 'iota'],
        [954, 'kappa'],
        [955, 'lambda'],
        [956, 'mu'],
        [957, 'nu'],
        [958, 'xi'],
        [959, 'omicron'],
        [960, 'pi'],
        [961, 'rho'],
        [962, 'final sigma'],
        [963, 'sigma'],
        [964, 'tau'],
        [965, 'upsilon'],
        [966, 'phi'],
        [967, 'chi'],
        [968, 'psi'],
        [969, 'omega']
      ]
    },
    {
      name: 'Greek Letters',
      characters: [
        [945, 'small letter alpha'],
        [946, 'small letter beta'],
        [947, 'small letter gamma'],
        [948, 'small letter delta'],
        [949, 'small letter epsilon'],
        [950, 'small letter zeta'],
        [951, 'small letter eta'],
        [952, 'small letter theta'],
        [953, 'small letter iota'],
        [954, 'small letter kappa'],
        [955, 'small letter lambda'],
        [956, 'small letter mu'],
        [957, 'small letter nu'],
        [958, 'small letter xi'],
        [959, 'small letter omicron'],
        [960, 'small letter pi'],
        [961, 'small letter rho'],
        [962, 'small letter final sigma'],
        [963, 'small letter sigma'],
        [964, 'small letter tau'],
        [965, 'small letter upsilon'],
        [966, 'small letter phi'],
        [967, 'small letter chi'],
        [968, 'small letter psi'],
        [969, 'small letter omega'],
        [913, 'capital letter alpha'],
        [914, 'capital letter beta'],
        [915, 'capital letter gamma'],
        [916, 'capital letter delta'],
        [917, 'capital letter epsilon'],
        [918, 'capital letter zeta'],
        [919, 'capital letter eta'],
        [920, 'capital letter theta'],
        [921, 'capital letter iota'],
        [922, 'capital letter kappa'],
        [923, 'capital letter lambda'],
        [924, 'capital letter mu'],
        [925, 'capital letter nu'],
        [926, 'capital letter xi'],
        [927, 'capital letter omicron'],
        [928, 'capital letter pi'],
        [929, 'capital letter rho'],
        [931, 'capital letter sigma'],
        [932, 'capital letter tau'],
        [933, 'capital letter upsilon'],
        [934, 'capital letter phi'],
        [935, 'capital letter chi'],
        [936, 'capital letter psi'],
        [937, 'capital letter omega']
      ]
    },
    {
      name: 'Arrows',
      characters: [
        [8592, 'leftwards arrow'],
        [8593, 'upwards arrow'],
        [8594, 'rightwards arrow'],
        [8595, 'downwards arrow'],
        [8596, 'left right arrow'],
        [8597, 'up down arrow'],
        [8598, 'north west arrow'],
        [8599, 'north east arrow'],
        [8600, 'south east arrow'],
        [8601, 'south west arrow'],
        [8602, 'leftwards arrow with stroke'],
        [8603, 'rightwards arrow with stroke'],
        [8604, 'leftwards wave arrow'],
        [8605, 'rightwards wave arrow'],
        [8606, 'leftwards two headed arrow'],
        [8607, 'upwards two headed arrow'],
        [8608, 'rightwards two headed arrow'],
        [8609, 'downwards two headed arrow'],
        [8610, 'leftwards arrow with tail'],
        [8611, 'rightwards arrow with tail'],
        [8612, 'leftwards arrow from bar'],
        [8613, 'upwards arrow from bar'],
        [8614, 'rightwards arrow from bar'],
        [8615, 'downwards arrow from bar'],
        [8616, 'up down arrow with base'],
        [8617, 'leftwards arrow with hook'],
        [8618, 'rightwards arrow with hook'],
        [8619, 'leftwards arrow with loop'],
        [8620, 'rightwards arrow with loop'],
        [8621, 'left right wave arrow'],
        [8622, 'left right arrow with stroke'],
        [8623, 'downwards zigzag arrow'],
        [8624, 'upwards arrow with tip leftwards'],
        [8625, 'upwards arrow with tip rightwards'],
        [8626, 'downwards arrow with tip leftwards'],
        [8627, 'downwards arrow with tip rightwards'],
        [8628, 'rightwards arrow with corner downwards'],
        [8629, 'downwards arrow with corner leftwards'],
        [8630, 'anticlockwise top semicircle arrow'],
        [8631, 'clockwise top semicircle arrow'],
        [8632, 'north west arrow to long bar'],
        [8633, 'leftwards arrow to bar over rightwards arrow to bar'],
        [8634, 'anticlockwise open circle arrow'],
        [8635, 'clockwise open circle arrow'],
        [8636, 'leftwards harpoon with barb upwards'],
        [8637, 'leftwards harpoon with barb downwards'],
        [8638, 'upwards harpoon with barb rightwards'],
        [8639, 'upwards harpoon with barb leftwards'],
        [8640, 'rightwards harpoon with barb upwards'],
        [8641, 'rightwards harpoon with barb downwards'],
        [8642, 'downwards harpoon with barb rightwards'],
        [8643, 'downwards harpoon with barb leftwards'],
        [8644, 'rightwards arrow over leftwards arrow'],
        [8645, 'upwards arrow leftwards of downwards arrow'],
        [8646, 'leftwards arrow over rightwards arrow'],
        [8647, 'leftwards paired arrows'],
        [8648, 'upwards paired arrows'],
        [8649, 'rightwards paired arrows'],
        [8650, 'downwards paired arrows'],
        [8651, 'leftwards harpoon over rightwards harpoon'],
        [8652, 'rightwards harpoon over leftwards harpoon'],
        [8653, 'leftwards double arrow with stroke'],
        [8654, 'left right double arrow with stroke'],
        [8655, 'rightwards double arrow with stroke'],
        [8656, 'leftwards double arrow'],
        [8657, 'upwards double arrow'],
        [8658, 'rightwards double arrow'],
        [8659, 'downwards double arrow'],
        [8660, 'left right double arrow'],
        [8661, 'up down double arrow'],
        [8662, 'north west double arrow'],
        [8663, 'north east double arrow'],
        [8664, 'south east double arrow'],
        [8665, 'south west double arrow'],
        [8666, 'leftwards triple arrow'],
        [8667, 'rightwards triple arrow'],
        [8668, 'leftwards squiggle arrow'],
        [8669, 'rightwards squiggle arrow'],
        [8670, 'upwards arrow with double stroke'],
        [8671, 'downwards arrow with double stroke'],
        [8672, 'leftwards dashed arrow'],
        [8673, 'upwards dashed arrow'],
        [8674, 'rightwards dashed arrow'],
        [8675, 'downwards dashed arrow'],
        [8676, 'leftwards arrow to bar'],
        [8677, 'rightwards arrow to bar'],
        [8678, 'leftwards thick arrow'],
        [8679, 'upwards thick arrow'],
        [8680, 'rightwards thick arrow'],
        [8681, 'downwards thick arrow'],
        [8682, 'upwards thick arrow from bar'],
        [8683, 'upwards thick arrow on pedestal'],
        [8684, 'upwards thick arrow on pedestal with horizontal bar'],
        [8685, 'upwards thick arrow on pedestal with vertical bar'],
        [8686, 'upwards thick double arrow'],
        [8687, 'upwards thick double arrow on pedestal'],
        [8688, 'rightwards thick arrow from wal'],
        [8689, 'north west arrow to corner'],
        [8690, 'south east arrow to corner'],
        [8691, 'up down thick arrow'],
        [8692, 'right arrow with smal circle'],
        [8693, 'downwards arrow leftwards of upwards arrow'],
        [8694, 'Three rightwards arrows'],
        [8695, 'leftwards arrow with vertical stroke'],
        [8696, 'rightwards arrow with vertical stroke'],
        [8697, 'left right arrow with vertical stroke'],
        [8698, 'leftwards arrow with double vertical stroke'],
        [8699, 'rightwards arrow with double vertical stroke'],
        [8700, 'left right arrow with double vertical stroke'],
        [8701, 'leftwards open-headed arrow'],
        [8702, 'rightwards open-headed arrow'],
        [8703, 'left right open-headed arrow'],
        [10146, 'black small arrowhead'],
      ]
    },
    {
      'name': 'Brackets',
      'characters': [
        [40, 'left parenthesis'],
        [41, 'right parenthesis'],
        [91, 'left square bracket'],
        [93, 'right square bracket'],
        [123, 'left curly bracket'],
        [125, 'right curly bracket'],
        [12296, 'left angle bracket'],
        [12297, 'right angle bracket'],
      ]
    },
    {
      name: 'Other',
      characters: [
        [9633, 'white square'],
        [9642, 'black small square'],
        [9643, 'white medium square'],
        [9745, 'ballot box with check'],
        [9786, 'white smiling face'],
        [9826, 'black diamond suit'],
        [9984, 'black safety scissors'],
        [9985, 'upper blade scissors'],
        [9986, 'black scissors'],
        [9987, 'lower blade scissors'],
        [9988, 'white scissors'],
        [9998, 'lower right pencil'],
        [10022, 'black diamond'],
        [10004, 'heavy check mark'],

      ]
    }
  ];
};

const charmapFilter = (charmap: Char[]): Char[] => {
  return Tools.grep(charmap, (item) => {
    return isArray(item) && item.length === 2;
  });
};

const getCharsFromOption = (optionValue: Char[] | (() => Char[]) | undefined): Char[] => {
  if (isArray(optionValue)) {
    return charmapFilter(optionValue);
  }

  if (typeof optionValue === 'function') {
    return optionValue();
  }

  return [];
};

const extendCharMap = (editor: Editor, charmap: CharMap[]): CharMap[] => {
  const userCharMap = Options.getCharMap(editor);
  if (userCharMap) {
    charmap = [{name: UserDefined, characters: getCharsFromOption(userCharMap)}];
  }

  const userCharMapAppend = Options.getCharMapAppend(editor);
  if (userCharMapAppend) {
    const userDefinedGroup = Tools.grep(charmap, (cg) => cg.name === UserDefined);
    if (userDefinedGroup.length) {
      userDefinedGroup[0].characters = [...userDefinedGroup[0].characters, ...getCharsFromOption(userCharMapAppend)];
      return charmap;
    }
    return charmap.concat({name: UserDefined, characters: getCharsFromOption(userCharMapAppend)});
  }

  return charmap;
};

const getCharMap = (editor: Editor): CharMap[] => {
  const groups = extendCharMap(editor, getDefaultCharMap());
  return groups.length > 1 ? [
    {
      name: 'All',
      characters: Arr.bind(groups, (g) => g.characters)
    }
  ].concat(groups) : groups;
};

export {
  getCharMap
};
